services:

  user-manager-service:
    build: ../users-manager
    ports:
      - "8090:8080"
    environment:
      BASE_URL_EMAIL_MANAGER: "http://email-manager-service:8080/emails"
      CB_SLIDING_WINDOW_SIZE: 10
      CB_MINIMUM_NUMBER_OF_CALLS: 10
      CB_FAILURE_RATE_THRESHOLD: 50
      CB_WAIT_DURATION_IN_OPEN_STATE: 30s
      RL_LIMIT_FOR_PERIOD: 6
      RL_LIMIT_REFRESH_PERIOD: 60s
      RETRY_MAX_ATTEMPTS: 3
      RETRY_WAIT_DURATION: 1s
      RETRY_ENABLE_EXPONENTIAL_BACKOFF: "true"
      RETRY_EXPONENTIAL_BACKOFF_MULTIPLIER: 2.0
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 512M

  email-manager-service:
    build: ../email-manager
    ports:
      - "8092:8080"
    environment:
      MAIL_HOST: "smtp.gmail.com"
      MAIL_PORT: "587"
      MAIL_USERNAME: "test@test"
      MAIL_PASSWORD: "your_password_here"
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 512M

volumes:
  mysql_user_data:
  mysql_account_data: